name: Submit New Benefit
description: Suggest a student benefit to add
title: "[Benefit]: "
labels: ["new-benefit"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the benefit
      description: Tell us about the student benefit - what is it, what do students get, and where can they sign up?
      placeholder: |
        Example: Cursor offers one free year of Cursor Pro for university students. It's an AI-powered code editor with 500 fast requests per month. Students can sign up at cursor.com/students
    validations:
      required: true
